meta_product_name: "Parser"
meta_title: "Parser - Fique salvo em um click"
meta_description: "A mellhor ptoteção enquanto você dirige."
meta_image: "cover.png"                       # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
